_format_version: "3.0"

services:
  - name: auth-service
    url: http://auth-service:3001/auth
    routes:
      - name: auth-routes
        paths:
          - /api/auth
        strip_path: true

  - name: task-service
    url: http://task-service:3002/tasks
    routes:
      - name: task-routes
        paths:
          - /api/tasks
        strip_path: true

  - name: team-service
    url: http://team-service:3003/teams
    routes:
      - name: team-routes
        paths:
          - /api/teams
        strip_path: true
